// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyRestaurantManagement.Data;

namespace MyRestaurantManagement.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210906120959_paymentid")]
    partial class paymentid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("MyRestaurantManagement.Models.CustomerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<long>("Contact")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Flat No 21, DBC Appartment, 1st Main, Mahadevapura, 560145",
                            Contact = 7799055675L,
                            Firstname = "Sanjeev"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Flat No 036, Signature Endure, 6th Cross, Mahadevapura, 560145",
                            Contact = 9645782213L,
                            Firstname = "Prashanth Jain"
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.CustomerOrderModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("OrderCreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("OrderFinishedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<long>("PaymentID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RateDetails")
                        .HasColumnType("text");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CustomerOrders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CustomerId = 1L,
                            OrderCreationDate = new DateTime(2021, 9, 6, 17, 39, 58, 103, DateTimeKind.Local).AddTicks(3713),
                            OrderFinishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatusId = 1,
                            PaymentID = 0L,
                            Rate = 2000m,
                            TableNumber = 22
                        },
                        new
                        {
                            Id = 2L,
                            CustomerId = 2L,
                            OrderCreationDate = new DateTime(2021, 9, 6, 17, 39, 58, 104, DateTimeKind.Local).AddTicks(5994),
                            OrderFinishedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatusId = 6,
                            PaymentID = 0L,
                            Rate = 600m,
                            TableNumber = 1
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.MenuModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Active")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("RestaurantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Menues");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = 0L,
                            Name = "Main Menu",
                            RestaurantId = 1L
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.OrderItemModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = 1L,
                            ProductId = 1L,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = 1L,
                            ProductId = 9L,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3L,
                            OrderId = 1L,
                            ProductId = 17L,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4L,
                            OrderId = 2L,
                            ProductId = 11L,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5L,
                            OrderId = 2L,
                            ProductId = 3L,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6L,
                            OrderId = 2L,
                            ProductId = 25L,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.OrderStatusModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Open"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Closed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Paid"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Preparing"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ready"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Out For Delivery"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Delivered"
                        },
                        new
                        {
                            Id = 10,
                            Name = "In Cart"
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.ProductCategoryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("RestaurantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Chinese",
                            RestaurantId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Bread",
                            RestaurantId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Soups",
                            RestaurantId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Veg Gravy",
                            RestaurantId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Non - Veg Gravy",
                            RestaurantId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Biriyani",
                            RestaurantId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Rice",
                            RestaurantId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Rolls",
                            RestaurantId = 1L
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.ProductModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Active")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PercentDiscount")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("ProductCategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Egg Noodles",
                            PercentDiscount = 0,
                            Price = 150m,
                            ProductCategoryId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Chicken Noodles",
                            PercentDiscount = 0,
                            Price = 200m,
                            ProductCategoryId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Veg Noodles",
                            PercentDiscount = 0,
                            Price = 120m,
                            ProductCategoryId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Roti",
                            PercentDiscount = 0,
                            Price = 20m,
                            ProductCategoryId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Naan",
                            PercentDiscount = 0,
                            Price = 40m,
                            ProductCategoryId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Butter Naan",
                            PercentDiscount = 0,
                            Price = 50m,
                            ProductCategoryId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Parota",
                            PercentDiscount = 0,
                            Price = 30m,
                            ProductCategoryId = 2L
                        },
                        new
                        {
                            Id = 8L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Tomato Soup",
                            PercentDiscount = 0,
                            Price = 80m,
                            ProductCategoryId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Chicken Soup",
                            PercentDiscount = 0,
                            Price = 120m,
                            ProductCategoryId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Sweet Corn",
                            PercentDiscount = 0,
                            Price = 100m,
                            ProductCategoryId = 3L
                        },
                        new
                        {
                            Id = 11L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Corn Masala",
                            PercentDiscount = 0,
                            Price = 140m,
                            ProductCategoryId = 4L
                        },
                        new
                        {
                            Id = 12L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Paneer Butter Masala",
                            PercentDiscount = 0,
                            Price = 180m,
                            ProductCategoryId = 4L
                        },
                        new
                        {
                            Id = 13L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Veg Curry",
                            PercentDiscount = 0,
                            Price = 150m,
                            ProductCategoryId = 4L
                        },
                        new
                        {
                            Id = 14L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Butter Chicken",
                            PercentDiscount = 0,
                            Price = 200m,
                            ProductCategoryId = 5L
                        },
                        new
                        {
                            Id = 15L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Chicken Masala",
                            PercentDiscount = 0,
                            Price = 200m,
                            ProductCategoryId = 5L
                        },
                        new
                        {
                            Id = 16L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Mutton Masala",
                            PercentDiscount = 0,
                            Price = 250m,
                            ProductCategoryId = 5L
                        },
                        new
                        {
                            Id = 17L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Egg Curry",
                            PercentDiscount = 0,
                            Price = 180m,
                            ProductCategoryId = 5L
                        },
                        new
                        {
                            Id = 18L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Mutton Biriyani",
                            PercentDiscount = 0,
                            Price = 300m,
                            ProductCategoryId = 6L
                        },
                        new
                        {
                            Id = 19L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Egg Biriyani",
                            PercentDiscount = 0,
                            Price = 180m,
                            ProductCategoryId = 6L
                        },
                        new
                        {
                            Id = 20L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Chicken Biriyani",
                            PercentDiscount = 0,
                            Price = 250m,
                            ProductCategoryId = 6L
                        },
                        new
                        {
                            Id = 21L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Prawns Biriyani",
                            PercentDiscount = 0,
                            Price = 200m,
                            ProductCategoryId = 6L
                        },
                        new
                        {
                            Id = 22L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Veg Fried Rice",
                            PercentDiscount = 0,
                            Price = 150m,
                            ProductCategoryId = 7L
                        },
                        new
                        {
                            Id = 23L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Egg Fried Rice",
                            PercentDiscount = 0,
                            Price = 180m,
                            ProductCategoryId = 7L
                        },
                        new
                        {
                            Id = 24L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Mix Fried Rice",
                            PercentDiscount = 0,
                            Price = 250m,
                            ProductCategoryId = 7L
                        },
                        new
                        {
                            Id = 25L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Chicken Roll",
                            PercentDiscount = 0,
                            Price = 80m,
                            ProductCategoryId = 8L
                        },
                        new
                        {
                            Id = 26L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Egg Roll",
                            PercentDiscount = 0,
                            Price = 60m,
                            ProductCategoryId = 8L
                        },
                        new
                        {
                            Id = 27L,
                            Active = 0L,
                            MenuId = 1L,
                            Name = "Chicken Shawarma",
                            PercentDiscount = 0,
                            Price = 90m,
                            ProductCategoryId = 8L
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.RestaurantModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Bengaluru",
                            ManagerName = "Rajiv Das",
                            Name = "Danish Restaurant Pvt. Ltd.",
                            PostalCode = "584732",
                            Street = "Main Street",
                            StreetNumber = 6
                        });
                });

            modelBuilder.Entity("MyRestaurantManagement.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
